from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from mongo_db import users_collection, expenses_collection, actions_collection
from pydantic import BaseModel


# Fast API instance
app = FastAPI()

# Define the origins that are allowed to talk to your server
origins = [
  "http://localhost:3000",  # Default React port
  "http://127.0.0.1:3000",
  "http://localhost:5173",  # Default Vite/React port
  "http://127.0.0.1:5173",
]

app.add_middleware(
  CORSMiddleware,
  allow_origins=origins,
  allow_credentials=True,
  allow_methods=["*"],  # Allows all methods (GET, POST, PUT, DELETE, etc.)
  allow_headers=["*"],  # Allows all headers
)

class LoginRequest(BaseModel):
  email: str
  password: str

example_users = { "admin@test.com": "admin", "user@test.com": "user"}

# === Endpoints ===

# --- Login / Users ---
@app.post("/login")
async def user_login(data: LoginRequest):
  stored_password = example_users.get(data.email)
  if stored_password and stored_password == data.password:
    return {
      "status": "success",
      "message": f"Welcome!",
      "user": data.email,
    } 
  
  raise HTTPException(
    status_code=status.HTTP_401_UNAUTHORIZED,
    detail='[User] Invalid email or password.'
  )

# --- Expenses ---

# - Get Function
# Returns an array of records (objects) located in the Database 
@app.get("/expenditure")
async def db_get_expenditure():
  # Exclude the autogenerated "_id" field in mongo db.
  cursor = expenses_collection.find({}, {"_id": 0})
  return [{**item} for item in cursor]

# - Add function
# Adds a record from submitForm into the database. Treated as a dict in python.
@app.post("/expenditure")
async def db_create_expense(expense: dict):
  result = expenses_collection.insert_one(expense)
  id = result.inserted_id
  return {"id": str(id)}

# - Delete function
# Remove a record from the database. Called by deleteExpenditure.
@app.delete("/expenditure/{expenditure_id}")
async def db_delete_expense(expenditure_id: str):
  status = expenses_collection.delete_one({"id": expenditure_id})
  if status.deleted_count == 1: # If a record has been successfully deleted...
    return {"message": f"[Delete] Item with id {expenditure_id} deleted"}
  else:
    raise HTTPException(
      status_code=status.HTTP_404_NOT_FOUND,
      detail=f"Item with id {expenditure_id} not found",
    )
  
# --- Actions ---