from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
from datetime import datetime
from mongo_db import users_collection, expenses_collection, actions_collection 



import bcrypt
import jwt

# Fast API instance
app = FastAPI()

# Define the origins that are allowed to talk to your server
origins = [
  "http://localhost:3000",  # Default React port
  "http://127.0.0.1:3000",
  "http://localhost:5173",  # Default Vite/React port
  "http://127.0.0.1:5173",
]

app.add_middleware(
  CORSMiddleware,
  allow_origins=origins,
  allow_credentials=True,
  allow_methods=["*"],  # Allows all methods (GET, POST, PUT, DELETE, etc.)
  allow_headers=["*"],  # Allows all headers
)


def hash_password(plain_password: str) -> str:
  password_bytes = plain_password.encode("utf-8")
  salt = bcrypt.gensalt(rounds=12)
  hash = bcrypt.hashpw(password_bytes, salt)
  return hash.decode("utf-8")

def check_password(plain_password: str, encrypted_password: str) -> bool:
  plain_bytes = plain_password.encode("utf-8")
  hash_bytes = encrypted_password.encode("utf-8")
  return bcrypt.checkpw(plain_bytes, hash_bytes) # returns true if both strings match


class user_data(BaseModel):
  email: str
  password: str
  role: Optional[str] = "user"

def add_user(data: user_data):
  exists = users_collection.find_one({"email": data.email})
  if exists:
    print(f"[User] User {data.email} already exists.")
    return
  users_collection.insert_one(
    {
      "email": data.email,
      "password": hash_password(data.password),
      "role": data.role,
    }
  )
  print(f"[User] {data.email} registered.")
  return {
    "status": "success",
    "message": f"User {data.email} registered.",
  }

add_user(user_data(email="admin@test.com", password="admin", role="admin"))
add_user(user_data(email="user1@test.com", password="user1", role="user"))
add_user(user_data(email="user2@test.com", password="user2", role="user"))



# === Endpoints ===
# --- Login / Users ---
class LoginRequest(BaseModel):
  email: str
  password: str

@app.post("/login")
async def user_login(form_data: LoginRequest):

  user = users_collection.find_one({"email": form_data.email})
  if not user:
    raise HTTPException(
      status_code=status.HTTP_401_UNAUTHORIZED,
      detail="[User] User not found."
    )
  
  if not check_password(form_data.password, user.get("password")):
    raise HTTPException(
      status_code=status.HTTP_401_UNAUTHORIZED,
      detail="[User] Incorrect username or password."
    )
  
  generic_action(action_log(email=user.get("email"), action="USER_LOGIN"))
  return {
    "status": "success",
    "message": "Welcome!",
    "user": form_data.email,
  }

# --- Expenses ---
# - Get Function
# Returns an array of records (objects) located in the Database 
@app.get("/expenditure")
async def db_get_expenditure():
  return expenses_collection.find({}, {"_id": 0}).to_list()
  # Exclude the autogenerated "_id" field in mongo db.

# - Add function
# Adds a record from submitForm into the database. Treated as a dict in python.
@app.post("/expenditure")
async def db_create_expense(expense: dict):
  result = expenses_collection.insert_one(expense)
  id = result.inserted_id
  return {"id": str(id)}

# - Delete function
# Remove a record from the database. Called by deleteExpenditure.
@app.delete("/expenditure/{expenditure_id}")
async def db_delete_expense(expenditure_id: str):
  status = expenses_collection.delete_one({"id": expenditure_id})
  if status.deleted_count == 1: # If a record has been successfully deleted...
    return {"message": f"[Delete] Item with id {expenditure_id} deleted"}
  else:
    raise HTTPException(
      status_code=status.HTTP_404_NOT_FOUND,
      detail=f"Item with id {expenditure_id} not found",
    )



# --- Action log ---
# Functions or endpoints that add an entry to the actions log.
class action_log(BaseModel):
  email: str
  action: str
  
def generic_action(log: action_log):
  actions_collection.insert_one(
    {
      "user": log.email,
      "action": log.action,
      "time": datetime.now()
    }
  )

def expense_action(log: action_log, expense: str):
  actions_collection.insert_one(
    {
      "user": log.email,
      "action": log.action,
      "time": datetime.now(),
      "description": expense
    }
  )

@app.get("/actions")
async def db_get_actions():
  return actions_collection.find({}, {"_id": 0}).to_list()